# Generated by Django 2.2.3 on 2020-06-16 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encoder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='image_tag',
        ),
    ]
